server.port=2323


spring.application.name=workstation
spring.application.version=0.0.1


# Custom path for Swagger UI (default: /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for OpenAPI json spec (default: /v3/api-docs)
springdoc.api-docs.path=/v3/api-docs